# rules_lean_grpc/proto.bzl
"""Rules for generating Lean code from Protocol Buffer definitions."""

load("@rules_proto//proto:defs.bzl", "ProtoInfo")
load("@rules_lean//lean:defs.bzl", "LeanGeneratedSourceInfo", "lean_library")

def _default_module_prefix(name):
    parts = []
    for raw in name.replace("-", "_").split("_"):
        if raw:
            parts.append(raw[0].upper() + raw[1:])
    return "".join(parts) if parts else "Proto"

def _module_prefix_path(module_prefix):
    return module_prefix.replace(".", "/")

def _proto_output_basename(src):
    if src.basename.endswith(".proto"):
        return src.basename[:-len(".proto")]
    return src.basename

def _proto_import_path(src, proto_source_root):
    """The canonical import path protoc records for a proto source (its path
    relative to the target's proto source root, handling strip_import_prefix
    virtual imports)."""
    if proto_source_root and proto_source_root != ".":
        root = proto_source_root + "/"
        if src.path.startswith(root):
            return src.path[len(root):]
    return src.path

def _proto_path_args(proto_info, proto_sources):
    seen = {}
    paths = []
    for path in proto_info.transitive_proto_path.to_list():
        if path not in seen:
            seen[path] = True
            paths.append(path)
    for src in proto_sources:
        if src.dirname and src.dirname not in seen:
            seen[src.dirname] = True
            paths.append(src.dirname)
    return paths

_LeanProtoLibraryGenInfo = provider(
    doc = "Information about pure Lean protobuf sources generated by protoc-gen-lean4.",
    fields = {
        "lean_srcs": "Generated Lean source files.",
        "module_prefix": "Lean module prefix used for generated modules.",
        "proto_paths": "Proto import paths (as protoc canonicalizes them) covered by this target.",
    },
)

def _lean_proto_generate_impl(ctx):
    proto_info = ctx.attr.proto[ProtoInfo]
    proto_sources = proto_info.direct_sources
    if not proto_sources:
        fail("No proto sources found")

    module_prefix = ctx.attr.module_prefix
    if not module_prefix:
        module_prefix = _default_module_prefix(ctx.label.name)
    module_path = _module_prefix_path(module_prefix)

    outputs = []
    copy_lines = []
    for src in proto_sources:
        base = _proto_output_basename(src)
        out = ctx.actions.declare_file(module_path + "/" + base + ".lean")
        outputs.append(out)
        copy_lines.append('mkdir -p "$(dirname \'{out}\')"'.format(out = out.path))
        copy_lines.append('cp "$TMP/{base}.lean" "{out}"'.format(base = base, out = out.path))

    # Imports of protos generated by other lean_proto_library targets resolve
    # to modules under those targets' prefixes.
    dep_module_entries = []
    for dep in ctx.attr.deps:
        info = dep[_LeanProtoLibraryGenInfo]
        for path in info.proto_paths:
            dep_module_entries.append(path + "@" + info.module_prefix)

    args = ctx.actions.args()
    for path in _proto_path_args(proto_info, proto_sources):
        args.add("--proto_path=" + path)
    args.add("--plugin=protoc-gen-lean4=" + ctx.executable._protoc_gen_lean4.path)
    args.add("--lean4_opt=lean4_prefix=" + module_prefix)
    if dep_module_entries:
        args.add("--lean4_opt=dep_modules=" + ";".join(dep_module_entries))
    args.add_all([src.path for src in proto_sources])

    command = """set -eu
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT
"{protoc}" --lean4_out="$TMP" "$@"
{copy_outputs}
""".format(
        protoc = ctx.executable._protoc.path,
        copy_outputs = "\n".join(copy_lines),
    )

    ctx.actions.run_shell(
        command = command,
        arguments = [args],
        # The action script intentionally uses standard shell/coreutils utilities
        # (mktemp, rm, mkdir, dirname, and cp). In hermetic package builds the
        # caller supplies those tools through the action environment's PATH.
        use_default_shell_env = True,
        inputs = depset(
            direct = list(proto_sources),
            transitive = [proto_info.transitive_sources],
        ),
        outputs = outputs,
        tools = [
            ctx.executable._protoc,
            ctx.executable._protoc_gen_lean4,
        ],
        mnemonic = "ProtoGenLean4",
        progress_message = "Generating pure Lean protobuf modules for %s" % ctx.label,
    )

    return [
        DefaultInfo(files = depset(outputs)),
        OutputGroupInfo(lean_srcs = depset(outputs)),
        LeanGeneratedSourceInfo(lean_srcs = depset(outputs)),
        _LeanProtoLibraryGenInfo(
            lean_srcs = depset(outputs),
            module_prefix = module_prefix,
            proto_paths = [
                _proto_import_path(src, proto_info.proto_source_root)
                for src in proto_sources
            ],
        ),
    ]

_lean_proto_generate = rule(
    implementation = _lean_proto_generate_impl,
    doc = "Generates pure Lean protobuf modules with the Lean protoc plugin.",
    provides = [LeanGeneratedSourceInfo, _LeanProtoLibraryGenInfo],
    attrs = {
        "proto": attr.label(
            doc = "The proto_library target to generate Lean code for.",
            mandatory = True,
            providers = [ProtoInfo],
        ),
        "module_prefix": attr.string(
            doc = "Lean module prefix for generated modules. Defaults to PascalCase(name).",
        ),
        "deps": attr.label_list(
            doc = "Codegen targets of other lean_proto_library targets whose protos this target imports.",
            providers = [_LeanProtoLibraryGenInfo],
        ),
        "_protoc": attr.label(
            default = "@protobuf//:protoc",
            executable = True,
            cfg = "exec",
        ),
        "_protoc_gen_lean4": attr.label(
            default = "@grpc_lean_protobuf//:protoc-gen-lean4",
            executable = True,
            cfg = "exec",
        ),
    },
)

def _gen_label(label):
    """The <name>_gen codegen target label for a lean_proto_library label."""
    if ":" in label:
        return label + "_gen"
    if "//" in label:
        return label + ":" + label.rsplit("/", 1)[-1] + "_gen"
    return label + "_gen"

def lean_proto_library(
        name,
        proto,
        module_prefix = None,
        proto_deps = None,
        deps = None,
        visibility = None,
        **kwargs):
    """Generates protobuf Lean modules and builds them as a lean_library.

    This macro uses the Lean `protoc-gen-lean4` plugin from
    `@grpc_lean_protobuf` to generate protobuf modules and pure-Lean gRPC
    service bindings; it emits no C++ adapter code.

    Args:
        name: Target name; also the default source of the module prefix.
        proto: proto_library with the protos to generate.
        module_prefix: override the Lean module prefix (default PascalCase(name)).
        proto_deps: other lean_proto_library targets whose protos this target's
            protos import; generated imports resolve to those targets' module
            prefixes and the compiled library depends on them.
        deps: extra Lean deps for the compiled library.
        visibility: standard visibility (also applied to the codegen target so
            downstream codegen rules — e.g. protovalidate — can read its
            provider).
        **kwargs: forwarded to the underlying lean_library.
    """
    gen_name = name + "_gen"
    _lean_proto_generate(
        name = gen_name,
        proto = proto,
        # Resolve the default here so it derives from the user-facing target
        # name, not the internal "<name>_gen" codegen target.
        module_prefix = module_prefix or _default_module_prefix(name),
        deps = [_gen_label(d) for d in (proto_deps or [])],
        visibility = visibility,
    )

    srcs_name = name + "_srcs"
    native.filegroup(
        name = srcs_name,
        srcs = [":" + gen_name],
        output_group = "lean_srcs",
        visibility = ["//visibility:private"],
    )

    lean_deps = [
        "@grpc_lean_protobuf//:protobuf",
        "@rules_lean_grpc//:grpc_lean",
    ]
    if proto_deps:
        lean_deps = lean_deps + proto_deps
    if deps:
        lean_deps = lean_deps + deps

    lean_library(
        name = name,
        srcs = [":" + srcs_name],
        strip_module_prefix = native.package_name(),
        deps = lean_deps,
        visibility = visibility,
        **kwargs
    )

LeanProtoLibraryGenInfo = _LeanProtoLibraryGenInfo
